apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppe-detection
  namespace: default
  labels:
    app: ppe-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppe-detection
  template:
    metadata:
      labels:
        app: ppe-detection
    spec:
      containers:
      - name: ppe-detection
        image: {{ .Values.ppeDetection.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ppe-data-pvc
          mountPath: /app/data
        ports:
        {{- range .Values.ppeDetection.ports }}
          - containerPort: {{ .port }}
        {{- end }}
      volumes:
      - name: ppe-data-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolume.name }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret.name }}
